version: "3"
services:
  chatApp:
    container_name: chat-app-server
    build:
      context: ./chat-app-server
      dockerfile: Dockerfile
    image: chat-app-server
    networks:
      - mysql
      - mongo
      - elasticsearch
    env_file:
      - ./chat-app-server/chat-app.env
    ports:
      - "8443:8443"
    volumes:
      - ./chat-app-server/war:/tomcat/apache-tomcat-9.0.73/webapps
      - ./src/main/resources:/chat-app-resources
    depends_on:
      - mysql
      - mongoDb
      - elasticsearch
  mysql:
    container_name: chat-app-mysql
    image: mysql/mysql-server:latest
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "8081:3306"
    environment:
      MYSQL_DATABASE: chatApp
      MYSQL_ROOT_PASSWORD: chatApp
      MYSQL_USER: user
      MYSQL_PASSWORD: chatApp
    networks:
      - mysql
  elasticsearch:
    container_name: chat-app-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.16
    ports:
      - "9201:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data:rw
    networks:
      - elasticsearch
    restart: unless-stopped
  mongoDb:
    container_name: chat-app-mongo
    image: mongo:5.0
    ports:
      - "8085:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - mongo

networks:
  mysql:
    driver: bridge
  mongo:
    driver: bridge
  elasticsearch:
    driver: bridge
